### ISSUE TITLE
liborocos-kdl.so.1.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by florian02100** [orocos/orocos_kinematics_dynamics#101]
Hi,

I'm Florian i work with KDL to solve ik problems.

But when i run my program i've this error : liborocos-kdl.so.1.4: cannot open shared object file: No such file or directory

Nevertheless i've this file in usr/local/lib and LD_LIBRARY = usr/local/lib.
Moreover in my program i've LIBS += "usr/local/lib/*.so".

So i don't understand, if you have any idea ..... ?

Thanks

**Comment by smits** [comment]
I think your path is missing a leading slash: "/usr/local/lib"

**Comment by smits** [comment]
Closing as this does not seem to be a KDL related problem.

**Comment by prashanthitata** [comment]
how do we upgrade from 1.3 to 1.4 that the path in /usr/local/lib is not missed?

**Comment by MatthijsBurgh** [comment]
@prashanthitata Your question is very unclear and probably not related to this closed issue. So please open a new issue.

P.S. responding to a closed issue, especially when it has been closed for a long time, is a bad habit, unless you are 100% sure it is the same problem.
