### ISSUE TITLE
chainjnttojacdotsolver.hpp not available in Indigo, Kinetic and Lunar versions

### ISSUE THREAD

**Issue by GuiRitter** [orocos/orocos_kinematics_dynamics#102]
Hi everyone.

This file is mentioned in the docs, but isn't present in the Indigo and Lunar installations of `orocos_kdl`.

[Here](http://answers.ros.org/question/266078/where-can-i-get-chainjnttojacdotsolver/) suggested that I added an issue here.

Thanks in advance.

**Comment by adamconkey** [comment]
+1 I am similarly trying to use this but it is not in the Kinetic release version. I'm going to try building from source until it's included.

**Comment by smits** [comment]
In the form it is in master it cannot be released to Kinetic as it is not ABI compatible, I'll need to find a patchset that includes that solver without breaking ABI backwards compatibility.

**Comment by smits** [comment]
This has been released in melodic.
