### ISSUE TITLE
Dynamic reconfiguring of a Chain object inside a solver e.g., ChainDynParam

### ISSUE THREAD

**Issue by xwavex** [orocos/orocos_kinematics_dynamics#103]
I need to dynamically change the dynamic parameters i.e. mass of a chain segment, which is used with a solver, such as e.g., ChainDynParam. Since I cannot allocate memory on the heap, it is not feasible for me to always create a new ChainDynParam object with the reconfigured chain as parameter.

What would be the right way to do this?

**Comment by ahoarau** [comment]
I think that was the point of #63 , but no news since 2015. I plus one this feature request !

**Comment by xwavex** [comment]
I just tried out the branch feature/solvers_use_reference_of_chain referenced by #63. At first glance it seems like that it properly compiles except for the **python_orocos_kdl** part. For me this is totally fine, since I don't use python at all.
In the next days I will integrate this KDL version into my controller code and see what happens.

**Comment by smits** [comment]
@xwavex Can you confirm if the latest master (which includes `solvers_use_reference_of_chain`) works for you and close the issue if yes?

**Comment by MatthijsBurgh** [comment]
outdated
