### ISSUE TITLE
Const correctness for operator* of class Frame2

### ISSUE THREAD

**Issue by mcopejans** [orocos/orocos_kinematics_dynamics#120]
The multiplication operator of class `Frame2` does not modify any member variables, so can be made const. ([link to code](https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/src/frames.hpp#L1121))

Both PRs listed below fix this issue in a different way by:
- directly adding const (potentially not ABI compatible, depending on system and compiler specifics for the `inline` keyword): https://github.com/orocos/orocos_kinematics_dynamics/pull/118
- deprecating non-const function and adding a const version: https://github.com/orocos/orocos_kinematics_dynamics/pull/119

Does anyone have a preference over one of both solutions?

**Comment by meyerj** [comment]
#118 was merged. We believe that it is fully ABI compatible.
