### ISSUE TITLE
No sign-in option in orocos forum

### ISSUE THREAD

**Issue by roboticsai** [orocos/orocos_kinematics_dynamics#134]
Hello i am learning orocos this days very hard. But when i get lot of build erros when practicing orocos tutorials and examples , i don't have any place to ask this question? Where should i as k this questions?
Why is orocos official forum page not accepting anyh new orocos user who is trying to learn orocos for hard real time control of robots?

**Comment by smits** [comment]
@meyerj @psoetens Can we reopen the forum for new users or do we move support to another platform?

**Comment by MatthijsBurgh** [comment]
Outdated
