### ISSUE TITLE
error: undefined reference to `KDL::epsilon'

### ISSUE THREAD

**Issue by roboticsai** [orocos/orocos_kinematics_dynamics#141]
Error is:

> 
> CMakeFiles/localisation.dir/localisation-component.cpp.o: In function 
> `Localisation::updateHook()':
> localisation-component.cpp:(.text._ZN12Localisation10updateHookEv[_ZN12Localisation10updateHookEv]+0xee): undefined reference to `KDL::Rotation::Quaternion(double, double, double, double)'
> localisation-component.cpp:(.text._ZN12Localisation10updateHookEv[_ZN12Localisation10updateHookEv]+0x101): undefined reference to `KDL::epsilon'
> localisation-component.cpp:(.text._ZN12Localisation10updateHookEv[_ZN12Localisation10updateHookEv]+0x129): undefined reference to `KDL::Rotation::GetRotAngle(KDL::Vector&, double) const'
> collect2: error: ld returned 1 exit status
> components/localisation/CMakeFiles/localisation.dir/build.make:100: recipe for target 'components/localisation/orocos/gnulinux/controller-youbot/liblocalisation-gnulinux.so' failed
> make[2]: *** [components/localisation/orocos/gnulinux/controller-youbot/liblocalisation-gnulinux.so] Error 1
> CMakeFiles/Makefile2:763: recipe for target 'components/localisation/CMakeFiles/localisation.dir/all' failed
> make[1]: *** [components/localisation/CMakeFiles/localisation.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2

I am compiling controller-youbot package from this github page, to build this i did this steps:

    cd controller-youbot
    cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd)/../../install
    make install

At the last 3rd step i get the above error. I have already installed the orocos kdl package along with orocos_toolchain by using command catkin_make_isolated --install. I have linked the given kdl library in components/localisation/CMakeLists.txt file as:

[include_directories(${USE_OROCOS_INCLUDE_DIRS} ${orocos_kdl_INCLUDE_DIRS})
target_link_libraries(localisation-component ${USE_OROCOS_LIBRARIES} ${orocos_kdl_LIBRARIES})](url)

What could be i missing. I also used the ros-kinetic-orocos_kdl package instead of this which i built from source but still same error comes.

**Comment by MatthijsBurgh** [comment]
outdated and CI runs fine.
