### ISSUE TITLE
Memory leak on accessing PyKDL Frame vector in 16.04

### ISSUE THREAD

**Issue by tfoote** [orocos/orocos_kinematics_dynamics#157]
Running the following small snippet will cause significant memory usage quickly. (~1% growth per second consumption on my laptop)

This looks similar to #129 but I'm not sure if it's the same since the behavior is quite different. It is reproduced on 16.04 but on 14.04 it does not leak memory.

```
#!/usr/bin/env python                                                           

import PyKDL

f = PyKDL.Frame(
    PyKDL.Rotation.Quaternion(0, 1, 0, 0),
    PyKDL.Vector(1, 0, 0))

while(True):
    res_x = f.p[0]
```

**Comment by MatthijsBurgh** [comment]
Please check [my comment](https://github.com/orocos/orocos_kinematics_dynamics/issues/41#issuecomment-573624235) in #41 for possible fixes

**Comment by MatthijsBurgh** [comment]
PR for PyKDL based on PyBind11 is open: #229

`python-sip` fix is also pending for approval in ubuntu launchpad, so that should also be released in a few weeks.

**Comment by MatthijsBurgh** [comment]
A fixed version of `python-sip` is now available on `updates`.

**Comment by MatthijsBurgh** [comment]
@smits could you create new releases on `kinetic` and `melodic` based on the same releases, but which  use the new version of `sip`?

**Comment by MatthijsBurgh** [comment]
16.04 has reached end-of-life
