### ISSUE TITLE
Help with KDL Jacobian changeRefPoint definition?

### ISSUE THREAD

**Issue by Levi-Armstrong** [orocos/orocos_kinematics_dynamics#166]
I want to make sure I understand this correctly. The method changeRefPoint requires a vector from the current ref point to the new ref point but it is unclear to me what frame is this vector is in. In the case of the kinematic chain is this vector represented in the base coordinate frame of the chain or the last segments frame?

**Comment by MatthijsBurgh** [comment]
@Levi-Armstrong Have you found your answer in the meantime?

**Comment by Levi-Armstrong** [comment]
I did.
