### ISSUE TITLE
Memory leak: Path_Circle does not delete orient ptr

### ISSUE THREAD

**Issue by martiniil** [orocos/orocos_kinematics_dynamics#177]
When `Path_Circle()` throws an exception, initialization of the object is not completed. In this case the destructor is not called, which is responsible for `delete orient`.

This issue could be resolved by delegating object initialization.

**Comment by martiniil** [comment]
This issue is still prevailing. Please reopen it.

**Comment by MatthijsBurgh** [comment]
I would suggest to delete `orient_` before throwing the exception. Much nicer solution in my opinion.
