### ISSUE TITLE
On ros2 branch, C++ standard is not set

### ISSUE THREAD

**Issue by PeterMitrano** [orocos/orocos_kinematics_dynamics#185]
The ros2 branch fails to compile because C++11 is not enabled. Not sure where the right place to fix this is, but I added `set(CMAKE_CXX_STANDARD 11)` to the `CMakeLists.txt` in orocos_kdl and now it compiles. This is specifically for the ros2 branch, I did not test the master branch. Maybe that's the wrong branch to use for compiling for ros2?

**Comment by MatteoRagni** [comment]
Setting `set(CMAKE_CXX_STANDARD 11)` fixes also a compilation issue on Ubuntu 16.04 with `gcc5`

**Comment by MatthijsBurgh** [comment]
There is no `ros2` branch in this repo, so...
