### ISSUE TITLE
Could not find SIP during build?

### ISSUE THREAD

**Issue by eugval** [orocos/orocos_kinematics_dynamics#191]
Hello, 

I am trying to follow the steps described in [this issue](https://github.com/orocos/orocos_kinematics_dynamics/issues/115) in order to get a PyKDL binding with python3 as the one I installed through ros only imports correctly with python2 .

I cloned the master branch in this repository and followed step by step the procedure described in the thread:
![image](https://user-images.githubusercontent.com/24697174/63779144-f8435280-c8dd-11e9-9eec-1cfc73de61d2.png)

When building python_orocos_kdl, I get the following error:
![image](https://user-images.githubusercontent.com/24697174/63779278-33de1c80-c8de-11e9-8e86-236f86c5d854.png)

I have installed SIP with pip3 : `pip3 install --user SIP` .
When I also type : `pip install --user SIP`, but I  the following : 
![image](https://user-images.githubusercontent.com/24697174/63779511-90413c00-c8de-11e9-84f7-424875770321.png)

my `PYTHONPATH` is the following: 
![image](https://user-images.githubusercontent.com/24697174/63779561-a949ed00-c8de-11e9-8cfb-95d2f40f6509.png)

I also seem to have sip in my system:
![image](https://user-images.githubusercontent.com/24697174/63787940-93dbbf80-c8ec-11e9-91ff-30e06f98bc4d.png)

Also:
![image](https://user-images.githubusercontent.com/24697174/63788124-d7362e00-c8ec-11e9-9529-10318217259d.png)

I am quite confused about this, I suspect I am having a path issue but I cannot figure it out! 

I would greatly appreciate any help understanding what is happening here, and how can I fix this as I am stuck trying to build the package!

**Comment by eugval** [comment]
My issue seemed to be that SIP was compiled and installed for python2, not python3. 

This has nothing to do with the pip package that is just a binding (Please correct me if I'm wrong).

To install it for python3, i followed the instructions in [here](https://github.com/Ultimaker/libArcus/issues/59).

After this, the build worked!

**Comment by MatthijsBurgh** [comment]
please close this issue
