### ISSUE TITLE
Broken links to documentation

### ISSUE THREAD

**Issue by wieset** [orocos/orocos_kinematics_dynamics#200]
Hi! The documentation links on http://wiki.ros.org/orocos_kinematics_dynamics are giving 404s, I assume because of your server outage in August, and the mailing list is unreachable.

Is the documentation that was previously at http://orocos.org/kdl/User_Manual now available somewhere else? Is it the same as the API documentation at http://docs.ros.org/melodic/api/orocos_kdl/html/? Will the content that was previously at http://orocos.org/kdl/ be recovered?

**Comment by smits** [comment]
there was an issue with www.orocos.org, this has been fixed and all content has been recovered.
