### ISSUE TITLE
macOS 10.15 Installation

### ISSUE THREAD

**Issue by milutter** [orocos/orocos_kinematics_dynamics#201]
I can install the python 3 bindings of PyKDL very easily on Ubuntu systems with conda, e.g.,

(1) compile & install orocos kdl per source
(2) installing sip via ```conda intall sip``` 
(3) compiling the python 3 bindings via  ```cmake .. -DPYTHON_VERSION=3 ```
(4) ```import PyKDL``` => everything works great

On macOS 10.15 the compilation and installation works fine. However, when I import PyKDL, I get a segmentation fault, i.e., ```Segmentation fault: 11```.

Has anybody experienced something similar? 
Has anybody achieved installing the python 3 binding on macOS 10.15?

I had PyKDL installed on my old mac but cannot reproduce this on my new mac with newer operating system.

System: Macbook Pro 2018 / conda environment / python 3.7

**Comment by MatthijsBurgh** [comment]
Outdated, not using sip anymore
