### ISSUE TITLE
What does the mathematical support of this function：T*I

### ISSUE THREAD

**Issue by AaronLee150102** [orocos/orocos_kinematics_dynamics#205]
What does the mathematical support of this function：operator*(const Frame& T,const RigidBodyInertia& I)；

**Comment by smits** [comment]
If T represents the Transform a_T_b (frame b expressed in coordinate system/frame a) and the rigid body inertia is expressed in b then this functions gives you the rigid body inertia expressed in a: a_I = a_T_b * b_I

**Comment by MatthijsBurgh** [comment]
No response, so assuming @smits answer is sufficient.
