### ISSUE TITLE
How to use the trajectory.dat file

### ISSUE THREAD

**Issue by tangbinbinyes** [orocos/orocos_kinematics_dynamics#206]
After running the sample code of trajectory_example, I got a trajectory.dat file. How do I use this file that records the motion trajectory to make my industrial robot move according to the trajectory? The file is just line by line numbers, I don't know how to use it.

**Comment by MatthijsBurgh** [comment]
As mentioned in the comments. You can visualize it. https://github.com/orocos/orocos_kinematics_dynamics/blob/e6c7059a396d28d772ea030dfc6c0db6af4824ef/orocos_kdl/examples/trajectory_example.cpp#L2-L9

Any other usage of this file is totally depending on how you want to use it. So out of scope of the library.
