### ISSUE TITLE
ChainDynParam inherits privately from SolverI

### ISSUE THREAD

**Issue by eratner** [orocos/orocos_kinematics_dynamics#207]
Hello, I am curious about ChainDynParam inheriting privately from SolverI. This prevents users of ChainDynParam from calling some useful methods inherited from SolverI, such as [getError](https://github.com/orocos/orocos_kinematics_dynamics/blob/1ae45bb2e0821586e74047b01f7cb48d913204f4/orocos_kdl/src/solveri.hpp#L119) or [strError](https://github.com/orocos/orocos_kinematics_dynamics/blob/1ae45bb2e0821586e74047b01f7cb48d913204f4/orocos_kdl/src/solveri.hpp#L125). Is there any reason not to change it?

https://github.com/orocos/orocos_kinematics_dynamics/blob/1ae45bb2e0821586e74047b01f7cb48d913204f4/orocos_kdl/src/chaindynparam.hpp#L47

Thanks!

**Comment by MatthijsBurgh** [comment]
I don't know. I also don't see any obstructions.

@smits is there any reasons for private/not public inheritance?

If not please approve #261
