### ISSUE TITLE
Noetic release?

### ISSUE THREAD

**Issue by sloretz** [orocos/orocos_kinematics_dynamics#218]
It looks like all dependencies of packages in this repo have been released into Noetic. Mind releasing this repo? That would unblock releasing repos which depend on this one.

http://repositories.ros.org/status_page/blocked_releases_noetic.html?q=id%3D%22orocos_kinematics_dynamics%22&s=6&r=1

**Comment by smits** [comment]
Ok, I'll talk to some people here to get it released.

**Comment by sloretz** [comment]
Might not need a Noetic release if https://github.com/ros/rosdistro/pull/23841 is merged

**Comment by sloretz** [comment]
It looks like this is no longer necessary. ROS Noetic will use the releases in the upstream Focal and Buster apt repos. Thanks for your time!
