### ISSUE TITLE
PyBind11 instead of SIP

### ISSUE THREAD

**Issue by MatthijsBurgh** [orocos/orocos_kinematics_dynamics#219]
Although the bugs in SIP have been fixed https://github.com/orocos/orocos_kinematics_dynamics/issues/41#issuecomment-578111408, a new release of `python-sip` is needed. A bug report if filed on LaunchPad https://github.com/orocos/orocos_kinematics_dynamics/issues/41#issuecomment-581128891, but no progress there yet.

A possible solution would be switching to [PyBind11](https://github.com/pybind/pybind11), as this needs to build from source, this can easily been included with submodules.
@zchen24 did most of the work, which I included in my fork, check https://github.com/MatthijsBurgh/orocos_kinematics_dynamics/tree/pybind11 for the current status.

**Comment by jf---** [comment]
This is an exciting avenue, do hope to see the `pybind11` land in master.
The perspective of sidestepping binder specific code, but being able to just use plain C++ is a huge win, impressive work...

**Comment by MatthijsBurgh** [comment]
@jf--- Thanks. I plan to finish my work by the end of the week or the start of next week. After which I will open a PR to merge it into master.

**Comment by MatthijsBurgh** [comment]
PR is open: #229
