### ISSUE TITLE
Build Error during make

### ISSUE THREAD

**Issue by Occy88** [orocos/orocos_kinematics_dynamics#227]
![Selection_019](https://user-images.githubusercontent.com/33660690/76384461-d039af00-6356-11ea-96ad-9b1fe5a2b5b1.png)

**Comment by meyerj** [comment]
There is a proposed fix for Python 3 support in https://github.com/orocos/orocos_kinematics_dynamics/pull/137.

Which branch are you building? The constant `Fixed` did not exist in `enum JointType` before https://github.com/orocos/orocos_kinematics_dynamics/pull/137.

**Comment by Occy88** [comment]
all done, didn't realize higher python3 versions were not supported

**Comment by MatthijsBurgh** [comment]
Python 3 support is included in #229
