### ISSUE TITLE
documentation suggestions

### ISSUE THREAD

**Issue by walchko** [orocos/orocos_kinematics_dynamics#248]
Hello! So there seems to be very little documentation with python examples on how to use this or am I missing something? I would suggest writing some helpful `readme.md` files with useful information. The website also seems to be missing any python examples. Also, I would suggest adding a LICENSE file to the repo ... it is pretty standard practice. Thanks!

**Comment by MatthijsBurgh** [comment]
#190 already describes the license issue.
#49 describes the documentation issue. An sphinx configuration is provided. So you can build the docs by generating yourself from source as backup option. But in General the API should be the same as c++. Though it doesn't include all, so it is a subset of the c++ API.

Feel free to open a PR to extend documentation, examples, etc.
