### ISSUE TITLE
PyKDL throwing segmentation fault after passing a str to Tree() method in ROS - Noetic 

### ISSUE THREAD

**Issue by Murtaza786-oss** [orocos/orocos_kinematics_dynamics#249]
Just installed ROS-Noetic and ran into this bug I suspect
![image](https://user-images.githubusercontent.com/54032524/82844779-11ffdd80-9ee2-11ea-8e5c-0dddeb944b5a.png)

It seems that PyKDL.Tree() method is not working because of a segmentation fault.
This error never used to occur on ROS/Melodic with Python 2.7. Can someone please provide a solution?

This is the package.xml from the python_orocos_kdl currently installed in ros-noetic,

![image](https://user-images.githubusercontent.com/54032524/82919078-d9a9df00-9f75-11ea-948d-074f6c8aa264.png)

Also, tried to build this repo  from source. But  landed up with these errors can you please help me?

![image](https://user-images.githubusercontent.com/54032524/82908602-81201500-9f68-11ea-8299-7fbd5e13c74c.png)

**Comment by MatthijsBurgh** [comment]
Did you initialize the submodule?

**Comment by Murtaza786-oss** [comment]
I am not sure how should I initialize it can you please explain it to me briefly?

**Comment by MatthijsBurgh** [comment]
`git submodule update --init`

**Comment by Murtaza786-oss** [comment]
It gives me this error 

`fatal: not a git repository (or any of the parent directories): .git`

**Comment by MatthijsBurgh** [comment]
Did you do it in the git folder?

**Comment by Murtaza786-oss** [comment]
ok thank you, I have successfully generated the PyKDL.so file which is in the path `/home/murtaza/catkin_ws3/devel_isolated/python_orocos_kdl/lib/python3.8/dist-packages/PyKDL.so`

but when I try to import PyKDL after compiling python still refers to the old path that is `/usr/lib/python3/dist-packages/PyKDL.cpython-38-x86_64-linux-gnu.so`. How can I alter this?

**Comment by MatthijsBurgh** [comment]
Add `/home/murtaza/catkin_ws3/devel_isolated/python_orocos_kdl/lib/python3.8/dist-packages` to your PYTHONPATH environment variable

**Comment by Murtaza786-oss** [comment]
I used catkin_make_isolated because I was getting the following error with catkin_make,

```
-- ~~  traversing 2 packages in topological order:
-- ~~  - orocos_kdl (plain cmake)
-- ~~  - python_orocos_kdl (plain cmake)
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_workspace.cmake:100 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:67 (catkin_workspace)


-- Configuring incomplete, errors occurred!
See also "/home/murtaza/catkin_ws3/build/CMakeFiles/CMakeOutput.log".
See also "/home/murtaza/catkin_ws3/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:320: cmake_check_build_system] Error 1
```

After adding to PYTHONPATH I get the following error,
`ImportError: /home/murtaza/catkin_ws3/devel_isolated/python_orocos_kdl/lib/python3.8/dist-packages/PyKDL.so: undefined symbol: _ZNK3KDL6Vector4NormEd`

**Comment by MatthijsBurgh** [comment]
Try using python catkin tools

**Comment by Murtaza786-oss** [comment]
So I installed the catkin tools package but it seems that it is supporting only py2 because I get syntax error when I try running catkin build like,

```
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 5, in <module>
    from catkin_tools.commands.catkin import main
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/commands/catkin.py", line 28, in <module>
    from catkin_tools.common import is_tty
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/common.py", line 23, in <module>
    import trollius as asyncio
  File "/usr/local/lib/python3.8/dist-packages/trollius/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.8/dist-packages/trollius/base_events.py", line 42, in <module>
    from . import tasks
  File "/usr/local/lib/python3.8/dist-packages/trollius/tasks.py", line 565
    def async(coro_or_future, loop=None):
        ^
SyntaxError: invalid syntax
```

**Comment by MatthijsBurgh** [comment]
It should work, but try indeed the python2 version of python catkin tools. You can still build PyKDL on python3.

**Comment by Murtaza786-oss** [comment]
Hello so I compiled the workspace using catkin build by using the building the catkin tools from src from this repo [(https://github.com/catkin/catkin_tools.git)]. I get the following error when I compile.

![image](https://user-images.githubusercontent.com/54032524/83034703-d4fa2f00-a038-11ea-83a8-06aaca0a4817.png)

**Comment by MatthijsBurgh** [comment]
Yes it is a warning, not an error. So no problems.

I see that the build_depend doesn't contain a condition. This should be fixed.

Also rosdistro has not specified any option for focal. This should be fixed.

**Comment by MatthijsBurgh** [comment]
@Murtaza786-oss The missing SIP shouldn't be a problem, because if you don't set `BUILD_PYKDL_PYBIND11`, it defaults to ON, so PyBind11 is used.

Could you confirm that you don't have any segfaults anymore?

**Comment by Murtaza786-oss** [comment]
yes, no segmentation faults anymore thank you for the support. It works fine now!

**Comment by MatthijsBurgh** [comment]
Problem solved, closing

**Comment by YeeCY** [comment]
> So I installed the catkin tools package but it seems that it is supporting only py2 because I get syntax error when I try running`catkin build`like,
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/catkin", line 5, in <module>
>     from catkin_tools.commands.catkin import main
>   File "/usr/local/lib/python3.8/dist-packages/catkin_tools/commands/catkin.py", line 28, in <module>
>     from catkin_tools.common import is_tty
>   File "/usr/local/lib/python3.8/dist-packages/catkin_tools/common.py", line 23, in <module>
>     import trollius as asyncio
>   File "/usr/local/lib/python3.8/dist-packages/trollius/__init__.py", line 21, in <module>
>     from .base_events import *
>   File "/usr/local/lib/python3.8/dist-packages/trollius/base_events.py", line 42, in <module>
>     from . import tasks
>   File "/usr/local/lib/python3.8/dist-packages/trollius/tasks.py", line 565
>     def async(coro_or_future, loop=None):
>         ^
> SyntaxError: invalid syntax
> ```

I got the same problem, how to fix that?

**Comment by MatthijsBurgh** [comment]
> It should work, but try indeed the python2 version of python catkin tools. You can still build PyKDL on python3.

@YeeCY Same problem, same solution ;)

`catkin_tools` is still broken on python3, (https://github.com/catkin/catkin_tools/issues/594)

**Comment by YeeCY** [comment]
> > It should work, but try indeed the python2 version of python catkin tools. You can still build PyKDL on python3.
> 
> @YeeCY Same problem, same solution ;)
> 
> `catkin_tools` is still broken on python3, ([catkin/catkin_tools#594](https://github.com/catkin/catkin_tools/issues/594))

Okay, so currently we can only `catkin_make` this repo with other packages in a workspace with python2, right?

And I choose to build the repo and install the headers into the system path without catkin, it works as well.

**Comment by MatthijsBurgh** [comment]
You can use `catkin_tools`. Out of the box only the python2 version of `catkin_tools` does work. With extra steps you can get the python3 version to work as well.

Both the python2 and python3 version of `catkin_tools` can build PyKDL for python2 and python3.

And indeed you use the plain `cmake/make` install procedure. Though this requires a manual update, while catkin will rebuild it automatically.

**Comment by YeeCY** [comment]
> You can use `catkin_tools`. Out of the box only the python2 version of `catkin_tools` does work. With extra steps you can get the python3 version to work as well.
> 
> Both the python2 and python3 version of `catkin_tools` can build PyKDL for python2 and python3.
> 
> And indeed you use the plain `cmake/make` install procedure. Though this requires a manual update, while catkin will rebuild it automatically.

Got it
