### ISSUE TITLE
Release into ROS Noetic

### ISSUE THREAD

**Issue by davetcoleman** [orocos/orocos_kinematics_dynamics#252]
Thanks for this great package! We're working on [releasing MoveIt Noetic](https://github.com/ros-planning/moveit/issues/2015), and this is one of the blocking packages. Can someone do a release please? @smits

**Comment by meyerj** [comment]
See https://github.com/orocos/orocos_kinematics_dynamics/issues/218 and the [Noetic migration guide](http://wiki.ros.org/noetic/Migration#Use_Orocos_KDL_and_BFL_rosdep_keys)

It was decided to use the system packages `liborocos-kdl` and `liborocos-kdl-dev` available for all target platforms instead.

**Comment by davetcoleman** [comment]
My bad, I didn't search the issue history. Closing :disappointed:
