### ISSUE TITLE
patching file orocos_kdl/CMakeLists.txt Hunk #1 FAILED at 42.

### ISSUE THREAD

**Issue by 1ADZX** [orocos/orocos_kinematics_dynamics#257]
Hello, your update caused me to compile my project with the following errors. How can I solve this problem?
2020-06-07 20:27:35 +0800: running
patch -p1 --forward
in directory /home/dzx/sonar_simulation/control/kdl
patching file orocos_kdl/CMakeLists.txt
Hunk #1 FAILED at 42.
1 out of 1 hunk FAILED -- saving rejects to file orocos_kdl/CMakeLists.txt.rej
Exit: pid 30740 exit 1

**Comment by MatthijsBurgh** [comment]
`patch` updates your files, this isn't compiling yet....

But you have probably local changes of yourself that prevents a clean update. So not really our responsibility I would say. So please provide more information if you think otherwise.
