### ISSUE TITLE
 Newest version of orocos kdl

### ISSUE THREAD

**Issue by DimitriEckert137** [orocos/orocos_kinematics_dynamics#263]
@smits 
Hi everyone

I tried to use the inverse dynamics solver for trees (documentation) from the kinematis and dynamics library (kdl). I have installed the newest version of kdl with :

sudo apt install ros-melodic-orocos-kdl

So it should be the newest version (1.4.0-0bionic.20200303.062327).

But when i looked at the folder in /opt/ros/melodic/include/kdl there was no treeidsolver_recursive_newton_euler.hpp file, although according to the above mentioned documentation and this github repository it should be there. I managed to do a workaround by simply copying the necessary files into the folder manually and adapting some others so they are compatible and it somehow works. But i guess this is a horrible way to do it and i am not sure if it is not going to break down when i try different stuff. I get some seg fault issues which i am not sure if they are linked to this patchy approach. 

Can anyone tell me how i would do this the "right" way?

I also tried to create an account on the orocos webpage but when i responded to the invitation email like required i got an "Undelivered Mail Returned to Sender". Is this website and the orocos project even running anymore?

(i am using ubuntu 18.04 and ros melodic)

Edit:

I also have tried to follow [this installation recipe](https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/INSTALL) though I know close to nothing about ho w to use cmake. So I downloaded the zip file from [here](https://github.com/orocos/orocos_kinematics_dynamics) (from the green "Clone or download button") and extracted it to my downloads folder. I went into the orocos_kinematics_dynamics-master/orocos_kdl/src folder. Then I followed exactly the instructions. Whithin the ccmake curse interface, when pressing the c button I got the error that I needed to add the following line at the top of the CMakeLists.txt:  `cmake_minimum_required(VERSION 3.10)`
which I did. Then I commented out the lines:
```
IF(${CMAKE_MINIMUM_REQUIRED_VERSION} VERSION_GREATER "2.8.12")
    MESSAGE(AUTHOR_WARNING "CMAKE_MINIMUM_REQUIRED_VERSION is now ${CMAKE_MINIMUM_REQUIRED_VERSION}. This check can be removed.")
ENDIF()
```
Twice to be exact once at line 21 once at line 70. 
I changed the CMAKE_INSTALL_PREFIX to: /opt/ros/melodic/include/kdl
Then I generated it.
After that I entered the command "make" and I got this error:

```
CMakeFiles/orocos-kdl.dir/CMakeFiles/feature_tests.cxx.o: In function `main':
feature_tests.cxx:(.text+0x0): multiple definition of `main'
CMakeFiles/orocos-kdl.dir/CMakeFiles/3.10.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:CMakeCXXCompilerId.cpp:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/orocos-kdl.dir/build.make:1784: recipe for target 'liborocos-kdl.so.' failed
make[2]: *** [liborocos-kdl.so.] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/orocos-kdl.dir/all' failed
make[1]: *** [CMakeFiles/orocos-kdl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

What did I do wrong? What do I need to change?

**Comment by MatthijsBurgh** [comment]
The released version in Melodic is `1.4.0`, see the `1.4.0` tag, https://github.com/orocos/orocos_kinematics_dynamics/releases/tag/v1.4.0.

The current master still show 1.4.0, as it has not been released, the version is not bumped yet.

You can compile it from source. Just clone the repo in your workspace, make sure all dependencies are installed and use catkin.

**Comment by DimitriEckert137** [comment]
Ok. So I cloned the repo into my catkin_ws/src folder. Then I ran 
`catkin build orocos_kdl `
Which worked fine.
Then I ran
`rosdep install orocos_kdl`
Which also worked fine (I can't find the name of the additional stuff that was installed though since I closed the terminal in the meantime. Is there a way to see what rosdep has installed?)
But now when I want to run my own package I get the following error:
```
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
/opt/ros/melodic/lib/rviz/rviz: symbol lookup error: /opt/ros/melodic/lib/libmoveit_dynamics_solver.so.1.0.4: undefined symbol: _ZNK3KDL6Vector4NormEv

```
After which rviz dies. I tried it without including any of the kdl stuff but the error still appeared. When I run rviz on its own with default configuration It works fine.
I looked into the launch file of my node I found this part:
```
 <!-- launch Rviz with MoveIt -->
    <include file="$(find ur3_e_moveit_config)/launch/moveit_rviz.launch">
      <arg name="config" value="true"/>
    </include>
```
The moveit_rviz.launch file looks like this:

```
<launch>

  <arg name="debug" default="false" />
  <arg unless="$(arg debug)" name="launch_prefix" value="" />
  <arg     if="$(arg debug)" name="launch_prefix" value="gdb --ex run --args" />

  <arg name="config" default="false" />
  <arg unless="$(arg config)" name="command_args" value="" />
  <arg     if="$(arg config)" name="command_args" value="-d $(find ur3_e_moveit_config)/launch/moveit.rviz" />
  
  <node name="$(anon rviz)" launch-prefix="$(arg launch_prefix)" pkg="rviz" type="rviz" respawn="false"
	args="$(arg command_args)" output="screen">
    <rosparam command="load" file="$(find ur3_e_moveit_config)/config/kinematics.yaml"/>
  </node>

</launch>
```

The loaded kinematics.yaml file:
```
manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
``` 

So maybe there is a conflict since rviz uses this kdl_kinematics_plugin and now with the orocos_kdl package installed it doesn't work anymore?
I honestly wouldn't know where to start looking for this 'QVector<int>' since the rviz part was not written by me.

**Comment by MatthijsBurgh** [comment]
I assume you have loaded your workspaces correct. In that case, this does show that other software isn't compatible with the current master. So you can't use that. You will need to remove all related files, source and compiled files.

**Comment by DimitriEckert137** [comment]
What exactly do you mean by "loading the workspace"? 
So you think I should try to completely get rid of the kdl_kinematic_plugin ?

**Comment by MatthijsBurgh** [comment]
No, get rid of `orocos_kdl` in your workspace. Use the system version

You need to source the `setup.bash` of your workspace to be available in your terminal. That is what I meant with loading your workspace.

**Comment by DimitriEckert137** [comment]
System version being the one I get by  `sudo apt install ros-melodic-orocos-kdl` ? 
In this version there is no tree inverse dynamics solver right?

Ok yes, i sourced it.

**Comment by MatthijsBurgh** [comment]
Yes that is the system version.
Yes, there is no `Tree inverse dynamics solver` in that version.

If want to use both the `Tree inverse dynamics solver` and other libraries, which the system versions are not compatible with the newest kdl. You will need to compile those libraries from source.

**Comment by DimitriEckert137** [comment]
Ok thank you very much. So I will switch t the system version and will try to convert my tree to a chain and use the chain id solver.
