### ISSUE TITLE
Incongruent licensing

### ISSUE THREAD

**Issue by veimox** [orocos/orocos_kinematics_dynamics#267]
Hi! 

Just by roaming around I have noticed that even though this package is LGPL the header in the [test-runner](https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/tests/test-runner.cpp) is GPL. Even though that the file is not distributed with the package (thus is not linked and there are no IP conflicts) it would be nice to rewrite that file from scratch and make use of the package's license.

What do you think?

**Comment by ahoarau** [comment]
Another question: would it be possible to change to a more permissible license ? ROS-I people are using BSD

**Comment by MatthijsBurgh** [comment]
Should be fixed
