### ISSUE TITLE
Gravity in ChainIdSolver_RNE

### ISSUE THREAD

**Issue by DimitriEckert137** [orocos/orocos_kinematics_dynamics#274]
Hi
I am working with the ChainIdSolver_RNE. I use kdl system version 1.4.0. For the [constructor](https://github.com/orocos/orocos_kinematics_dynamics/blob/eaa92da4bbc2f6156d1f1a895c76ac16fd832a20/orocos_kdl/src/chainidsolver_recursive_newton_euler.cpp#L27) one needs to add a gravity vector. I see that in the constructor the negative of this vector is taken. So if I want to initialize the solver with a "normal" gravity vector (9.81m/s^2 towards the ground) how would the "grav" vector look like that I need to pass? Like `KDL::Vector g(0.0, 0.0, -9.81);`? Or `KDL::Vector g(0.0, 0.0, 9.81);`?
And generally what Units are used in kdl? Meters, kilograms, radians and seconds I guess?

**Comment by MatthijsBurgh** [comment]
I think this answers your question:
https://github.com/orocos/orocos_kinematics_dynamics/blob/a7a8d282a5a94948176f2c5af58fbd047d849030/orocos_kdl/models/puma560test.cpp#L44

And yes, KDL uses SI units.
