### ISSUE TITLE
Move real with toeques calculated by kdl

### ISSUE THREAD

**Issue by abradanek** [orocos/orocos_kinematics_dynamics#286]
Hi,

I want use kdl library to calculate effort for franka robot. Right now I calculate effort from PID, which is used to move the robot. As we can see on the picture below effort calculated by kdl (orange) is similar to real data read from franka robot (blue). To move robot we need to assign effort without gravity(kdl_filtered(red) on the picture) which is similar to calculated pid(green) values. So, when i pass kdl_filtered(red) values to robot - effort is not enough to start moving, how to solve this issue?
![torques_figure](https://user-images.githubusercontent.com/35931273/93322090-3c6c0280-f813-11ea-8317-662e237c35eb.png)

**Comment by MatthijsBurgh** [comment]
If the robot doesn't move either the gravity or friction is preventing it from moving. So look into that.

But how to get your robot moving is not related to KDL. So I am closing this issue. Good luck with getting your robot working.
