### ISSUE TITLE
Can't compile python_orocos_kdl using Python3 bindings

### ISSUE THREAD

**Issue by seanng-1** [orocos/orocos_kinematics_dynamics#291]
Hi, so I am using Ubuntu 18.04 on my virtual machine and have followed the install instructions in travis.yml.

I am successfully able to compile orocos_kdl but when I try to compile python_orocos_kdl using Python3 bindings I get the following error:

![Screenshot from 2020-10-15 13-01-55](https://user-images.githubusercontent.com/58413041/96072013-a517cf00-0ee6-11eb-8a3e-e4eca13cc06c.png)

I have tried different branches of the repository to test if it was a recent problem but this error continues to occur with any version that I have attempted to compile.

 I'm using sip version 4.19.7 and have installed all the following : libeigen3-dev libcppunit-dev python-sip-dev python3-sip-dev python-psutil python3-psutil python-future python3-future

I apologise for the poor formatting as this is my first time opening an issue.

**Comment by MatthijsBurgh** [comment]
Just use your catkin tool of preference to build PyKDL in a catkin workspace.

**Comment by seanng-1** [comment]
> Just use your catkin tool of preference to build PyKDL in a catkin workspace.

I have tried this and it still did not work.

**Comment by MatthijsBurgh** [comment]
You need to update the pybind11 submodule: `git submodule update --init`
