### ISSUE TITLE
cannot pass weight matrix to ChainIkSolverPos_LMA() class in PyKDL 

### ISSUE THREAD

**Issue by radhen** [orocos/orocos_kinematics_dynamics#292]
I have PyKDL installed in ROS and I am using it with Python 2.7. 

Is it possible to pass my own **weight matrix** to ChainIkSolverPos_LMA solver in PyKDL? Below is the constructor for the ChainIkSolverPos_LMA() class, 

`ChainIkSolverPos_LMA (const KDL::Chain &_chain, const Eigen::Matrix< double, 6, 1 > &_L, double _eps=1E-5, int _maxiter=500, double _eps_joints=1E-15)`

and L is the **weight matrix**. I can pass all the other arguments but not L. 
I am creating a eigen matrix in python like this

`weight_matrix = eigen.Matrix6D.Identity()`

and passing that as L, but I get the following error 

`
  File "allegro_contour_5_pykdl.py", line 79, in __init__
    self.ik_p_LMA = kdl.ChainIkSolverPos_LMA(chain=self.arm_chain, L=self.weight_matrix)
TypeError: arguments did not match any overloaded call:
  ChainIkSolverPos_LMA(chain: Chain, eps: float = 1e-05, _maxiter: int = 500, _eps_joints: float = 1e-15): 'L' is not a valid keyword argument
  ChainIkSolverPos_LMA(ChainIkSolverPos_LMA): 'L' is not a valid keyword argument
`

Is the full constructor for ChainIkSolverPos_LMA( ) class not available in Python 2.7 ?

**Comment by MatthijsBurgh** [comment]
I am not sure if you are using a released version of KDL/PyKDL or the master branch.

But I think this applies to both. Both for the PyBind11 version(only master) and the SIP version(released and master) of PyKDL only the short constructor is available, so matching https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/src/chainiksolverpos_lma.hpp#L108.

A constructor like https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/src/chainiksolverpos_lma.hpp#L95 is not (yet) available in PyKDL.

**Comment by radhen** [comment]
Good to know. Thank you :)
