### ISSUE TITLE
Properly update version number during release

### ISSUE THREAD

**Issue by trainman419** [orocos/orocos_kinematics_dynamics#30]
It looks like the minor version of the orocos_kdl library was updated in the most recent release, and it's breaking builds for users (myself included).

More details here: http://answers.ros.org/question/116401/cant-link-to-liborocos-kdlso11/

Please don't do this in the future, or at least make some effort to make the upgrade path cleaner. Spending 20 minutes rebuilding my entire workspace is unacceptable.

**Comment by smits** [comment]
Closing this as it's not a real issue, but more of a policy that we will try to follow in the future.
