### ISSUE TITLE
module 'PyKDL' has no attribute 'Tree'

### ISSUE THREAD

**Issue by seanng-1** [orocos/orocos_kinematics_dynamics#303]
I am trying to use PyKDL alongside the kdl_parser package (https://github.com/ros/kdl_parser) and I encounter this error.

![image](https://user-images.githubusercontent.com/58413041/100687331-d16ea880-33cb-11eb-9611-e7f290bc940f.png)

I installed PyKDL using the install instructions found here https://github.com/orocos/orocos_kinematics_dynamics/blob/master/python_orocos_kdl/INSTALL.md using the catkin method. I am using Python3.

I am using the latest version of the commit so I'm not too sure why this isn't working.

**Comment by MatthijsBurgh** [comment]
Did you compile using the python3?

**Comment by seanng-1** [comment]
I had compiled using catkin but used the manual compilation instructions for Python3 and it seems to be working now.
