### ISSUE TITLE
ROS2 package failed: orocos_kdl

### ISSUE THREAD

**Issue by mkeyno** [orocos/orocos_kinematics_dynamics#305]
I've tried yo build the ROS2 package, however, colon build stop on making `orocos_kdl` lib

```
Starting >>> orocos_kdl
[Processing: fastrtps, orocos_kdl]                                             
--- stderr: orocos_kdl                                                         
CMakeFiles/orocos-kdl.dir/segment.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make[2]: *** [src/liborocos-kdl.so.1.4.0] Error 1
make[1]: *** [src/CMakeFiles/orocos-kdl.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< orocos_kdl [39.0s, exited with code 2]
Aborted  <<< fastrtps [6min 33s]  
```

**Comment by MatthijsBurgh** [comment]
Can you provide an tree of the RELEVANT folders/files in the build folder?

**Comment by mkeyno** [comment]
@MatthijsBurgh  you mean this file 
[t.txt](https://github.com/orocos/orocos_kinematics_dynamics/files/5679309/t.txt)

**Comment by MatthijsBurgh** [comment]
Yes, that is what I mean.

The file seems to be available on line 5314. So I don't know what it absolute path it is looking for.

**Comment by mkeyno** [comment]
@MatthijsBurgh  there is nothing on `segment.cpp.o` file, I tried to replace it with another file from other VM Linux with fully installed ROS2 , but the error stand still

**Comment by MatthijsBurgh** [comment]
What do you mean with "there is nothing on `segment.cpp.o`"?

**Comment by mkeyno** [comment]
@MatthijsBurgh ,  it's an empty file
why thre is no segment.cpp file in source files 
there is segment.cpp file in ROS repo but not in ROS2

**Comment by MatthijsBurgh** [comment]
Ok, what is the ROS2 repo? I don't know what these people do

**Comment by MatthijsBurgh** [comment]
The ROS2 repo is way out of sync with this repo, which is the original one.

I suggest you ask them to get up-to-date with this repo and/or open a PR to get some of their changes in this repo.

I can't help you further for now.

**Comment by MatthijsBurgh** [comment]
Stale issue
