### ISSUE TITLE
KDL::ChainIkSolverPos_LMA is length unit sensitive

### ISSUE THREAD

**Issue by Bihlerben** [orocos/orocos_kinematics_dynamics#33]
It makes a difference, whether a kinematic chain is defined with millimeter length units or meter length units. The forward kinematics solver KDL::ChainFkSolverPos_recursive gives the same solution in my example, but the inverse kinematics solver KDL::ChainIkSolverPos_LMA gives different results.

I have introduced a length scaling parameter to my code and the results are as expected only if I divide all my lengths (given in millimeter) by 1000. Otherwise the solver won't find a solution.

Excerpts from my code:

double lengthFactor = 1e-3;
...
		// Add A1.
		chain.addSegment(
				KDL::Segment(KDL::Joint(KDL::Joint::RotZ, -1.0, 0.0),
						KDL::Frame(
								KDL::Vector(350.0 * lengthFactor, 0.0 * lengthFactor,
										750.0 * lengthFactor))));
...
KDL::ChainIkSolverPos_LMA lmaSolver(chain);

for (int index = 0; index < 6; ++index)
{
	q_init(index) = 0.0;
}

ret = lmaSolver.CartToJnt(q_init, F_dest, q);

Here the solver will give the expected results (all joint angle values correct and "close to zero"). But when I change lengthFactor to 1.0, the solver won't find a solution and the iterate will contain angle values of several thousand degrees. I have played with the epsilon values passed to the solver constructor, but they don't make difference.

My workaround with the length factor works, therefore I have no problem with the solver right now. Still this seems to be a bug to me.

**Comment by smits** [comment]
The probable cause is actually documented: https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/src/chainiksolverpos_lma.hpp#L52-L56

have you tried to use the task space weighting matrix, to increase the weight on the translations?

**Comment by Bihlerben** [comment]
Thank you very much for your answer. You are right. I hadn't tried that yet. Now I use these commands:

		Eigen::Matrix<double, 6, 1> weightingMatrix;

		weightingMatrix(0) = 1.0e-3;
		weightingMatrix(1) = 1.0e-3;
		weightingMatrix(2) = 1.0e-3;
		weightingMatrix(3) = 1.0;
		weightingMatrix(4) = 1.0;
		weightingMatrix(5) = 1.0;

		KDL::ChainIkSolverPos_LMA levenbergMarquardtSolver(kinematicChain,
				weightingMatrix);

This makes the solver work well even if I give the translations in millimeter.

Even though this seems to have been already documented, I find it very hard to get that information from the documentation. Adding two more lines and/or giving an example for the weighting matrix in the documentation might be a great help for novices like me.

**Comment by jf---** [comment]
+1 this indeed has a dramatic impact on performance, hence mentioned this explicitly in the  documentation would be much welcomed. thanks for the pointer to the source code Ruben, that's interesting...
