### ISSUE TITLE
Inconsistent license in orocos_kdl/debian

### ISSUE THREAD

**Issue by ralph-lange** [orocos/orocos_kinematics_dynamics#330]
According to [orocos_kdl/COPYING](https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/COPYING) and the headers of all source files (except issue https://github.com/orocos/orocos_kinematics_dynamics/issues/267) the library is licensed under LGPL.

The [copyright](https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/debian/copyright) file in the [orocos_kdl/debian](https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/debian/) folder however states that the library is licensed under GPL. Could you clarify this, please?

**Comment by ralph-lange** [comment]
Relates to https://github.com/orocos/orocos_kinematics_dynamics/issues/190.

**Comment by AndyZe** [comment]
As I understand it, this matters because any project using Orocos/KDL inherits the GPL license. That's quite a few open-source projects!

**Comment by MatthijsBurgh** [comment]
@smits @meyerj

**Comment by smits** [comment]
> The copyright file in the orocos_kdl/debian folder however states that the library is licensed under GPL. Could you clarify this, please?

That should be updated, the correct license is LGPL.

**Comment by ralph-lange** [comment]
Could you please also update orocos_kdl/tests/test-runner.cpp, cf. https://github.com/orocos/orocos_kinematics_dynamics/issues/267?

**Comment by MatthijsBurgh** [comment]
@ralph-lange could please apply the desired changes yourself and open a PR?

**Comment by ralph-lange** [comment]
Such a contribution to a new repository involves not inconsiderable internal process work for me and would take several days. Moreover, changes to the copyright header should be made by the original author. The simplest thing would be if he simply remove lines 1 through 16 from https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/tests/test-runner.cpp. Then, the LGPL license from the repository root applies.

**Comment by MatthijsBurgh** [comment]
I don't think the changes are that much.

It seems that you already did enough work to find out that the test runner is the only file that needs to be changed. So it wouldn't have been that much extra work. If other changes are needed, please open a PR or drop the line numbers in a new issue if you don't want to edit the lines yourself.

**Comment by ralph-lange** [comment]
Thank you very much for resolving the issue in the test folder, @MatthijsBurgh. The issue in the debian folder can be resolved in the same way. If you can remove the copyright file there, the LGPL license from the parent folder will apply.

**Comment by MatthijsBurgh** [comment]
Changed the copyright in the debian folder to LGPL.

**Comment by ralph-lange** [comment]
Thank you very much for resolving this issue!
