### ISSUE TITLE
object has no attribute 'ChainJntToJacDotSolver'  when I use Python 

### ISSUE THREAD

**Issue by Lejou** [orocos/orocos_kinematics_dynamics#332]
ROS: Melodic
IDE: Python

![image](https://user-images.githubusercontent.com/33564160/119626535-e89fc780-be3d-11eb-97b5-13756c184c0d.png)

When I use PyKDL in Python, the strange error has appeared.
Most classes, like ChainJntToJacSolver,ChainDynParam,ChainFkSolverPos_recursive, can be used correctly with atuo-complete in python. But when I want to use class of "ChainJntToJacDotSolver", it is said that:

Traceback (most recent call last):
  File "./dynamic_test.py", line 61, in <module>
    jacDot_kdl = kdl.ChainJntToJacDotSolver(chain)
AttributeError: 'module' object has no attribute 'ChainJntToJacDotSolver'

And I cannot use auto-complete to find this class when I use PyKDL.

Anyone knows the reason? Does this class not exist in PyKDL lib?

**Comment by MatthijsBurgh** [comment]
This one is not included in the 1.4 release. Similar to #327. So you will need to build from source if you want to use that solver in python.

**Comment by Lejou** [comment]
Appreciate!!
