### ISSUE TITLE
Noetic Release

### ISSUE THREAD

**Issue by jordan-palacios** [orocos/orocos_kinematics_dynamics#348]
Hello,

Are there any plans of releasing this repo under noetic?

Thanks.

**Comment by meyerj** [comment]
> Hello,
> 
> Are there any plans of releasing this repo under noetic?
> 
> Thanks.

It was decided to use the versions released into [Debian](https://packages.debian.org/liborocos-kdl-dev) and [Ubuntu](https://packages.ubuntu.com/liborocos-kdl-dev) instead for Noetic:

- https://github.com/orocos/orocos_kinematics_dynamics/issues/218
- https://github.com/orocos/orocos_kinematics_dynamics/issues/288
- https://github.com/orocos/orocos_kinematics_dynamics/issues/289

See also http://wiki.ros.org/noetic/Migration#Use_Orocos_KDL_and_BFL_rosdep_keys.
