### ISSUE TITLE
segmentation fault while importing PyKDL

### ISSUE THREAD

**Issue by kashifzr** [orocos/orocos_kinematics_dynamics#362]
<pre><font color="#729FCF"><b>~/ros2learn/experiments/examples/MARA</b></font>$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
&gt;&gt;&gt; import PyKDL
Segmentation fault (core dumped)
<font color="#8AE234"><b>cde@cde-MS-7A64</b></font>:<font color="#729FCF"><b>~/ros2learn/experiments/examples/MARA</b></font>$ python
Python 2.7.17 (default, Feb 27 2021, 15:10:58) 
[GCC 7.5.0] on linux2
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
&gt;&gt;&gt; import PyKDL
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
ImportError: /opt/ros/melodic/lib/python2.7/dist-packages/PyKDL.so: undefined symbol: _ZN3KDL25ChainIkSolverVel_pinv_nso28updateInternalDataStructuresEv
&gt;&gt;&gt; 
</pre>

Unable to resolve issue Related PyKDL

**Comment by MatthijsBurgh** [comment]
How did you install orocos_kdl, the cpp library? What is the version of the cpp library?

**Comment by kashifzr** [comment]
<pre><font color="#8AE234"><b>cde@cde-MS-7A64</b></font>:<font color="#729FCF"><b>~/orocos_kinematics_dynamics/orocos_kdl/build</b></font>$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Orocos KDL version  (1.5.1)
-- Using CATKIN_DEVEL_PREFIX: /home/cde/orocos_kinematics_dynamics/orocos_kdl/build/devel
-- Using CMAKE_PREFIX_PATH: /home/cde/ros2_mara_ws/install;/opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version &quot;2.7.17&quot;, minimum required is &quot;2&quot;) 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/cde/orocos_kinematics_dynamics/orocos_kdl/build/test_results
-- Found gtest sources under &apos;/usr/src/googletest&apos;: gtests will be built
-- Found gmock sources under &apos;/usr/src/googletest&apos;: gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version &quot;2.7.17&quot;) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- Setting build type to &apos;Release&apos;
-- Performing Test HAVE_STL_CONTAINER_INCOMPLETE_TYPES
-- Performing Test HAVE_STL_CONTAINER_INCOMPLETE_TYPES - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cde/orocos_kinematics_dynamics/orocos_kdl/build
<font color="#8AE234"><b>cde@cde-MS-7A64</b></font>:<font color="#729FCF"><b>~/orocos_kinematics_dynamics/orocos_kdl/build</b></font>$ ls
<font color="#729FCF"><b>atomic_configure</b></font>        CTestCustom.cmake    orocos_kdl-config.cmake
<font color="#729FCF"><b>catkin</b></font>                  CTestTestfile.cmake  orocos_kdl-config-version.cmake
<font color="#729FCF"><b>catkin_generated</b></font>        <font color="#729FCF"><b>devel</b></font>                orocos_kdl.pc
CATKIN_IGNORE           <font color="#729FCF"><b>doc</b></font>                  orocos-kdl.pc
CMakeCache.txt          <font color="#729FCF"><b>examples</b></font>             OrocosKDLTargets.cmake
<font color="#729FCF"><b>CMakeFiles</b></font>              <font color="#729FCF"><b>gtest</b></font>                <font color="#729FCF"><b>src</b></font>
cmake_install.cmake     Makefile             <font color="#729FCF"><b>test_results</b></font>
CTestConfiguration.ini  <font color="#729FCF"><b>models</b></font>               <font color="#729FCF"><b>tests</b></font>
<font color="#8AE234"><b>cde@cde-MS-7A64</b></font>:<font color="#729FCF"><b>~/orocos_kinematics_dynamics/orocos_kdl/build</b></font>$ make
<font color="#AD7FA8"><b>Scanning dependencies of target orocos-kdl</b></font>
[  1%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/articulatedbodyinertia.cpp.o</font>
[  2%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chain.cpp.o</font>
[  4%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chaindynparam.cpp.o</font>
[  5%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainexternalwrenchestimator.cpp.o</font>
[  7%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainfdsolver_recursive_newton_euler.cpp.o</font>
[  8%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainfksolverpos_recursive.cpp.o</font>
[ 10%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainfksolvervel_recursive.cpp.o</font>
[ 11%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainhdsolver_vereshchagin.cpp.o</font>
[ 13%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainidsolver_recursive_newton_euler.cpp.o</font>
[ 14%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainidsolver_vereshchagin.cpp.o</font>
[ 16%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolverpos_lma.cpp.o</font>
[ 17%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolverpos_nr.cpp.o</font>
[ 19%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolverpos_nr_jl.cpp.o</font>
[ 20%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolvervel_pinv.cpp.o</font>
[ 22%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolvervel_pinv_givens.cpp.o</font>
[ 23%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolvervel_pinv_nso.cpp.o</font>
[ 25%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolvervel_wdls.cpp.o</font>
[ 26%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainjnttojacdotsolver.cpp.o</font>
[ 28%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/chainjnttojacsolver.cpp.o</font>
[ 29%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/frameacc.cpp.o</font>
[ 31%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/frames.cpp.o</font>
[ 32%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/frames_io.cpp.o</font>
[ 34%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/framevel.cpp.o</font>
[ 35%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/jacobian.cpp.o</font>
[ 37%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/jntarray.cpp.o</font>
[ 38%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/jntarrayacc.cpp.o</font>
[ 40%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/jntarrayvel.cpp.o</font>
[ 41%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/jntspaceinertiamatrix.cpp.o</font>
[ 43%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/joint.cpp.o</font>
[ 44%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/kinfam_io.cpp.o</font>
[ 46%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/path.cpp.o</font>
[ 47%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/path_circle.cpp.o</font>
[ 49%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/path_composite.cpp.o</font>
[ 50%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/path_cyclic_closed.cpp.o</font>
[ 52%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/path_line.cpp.o</font>
[ 53%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/path_point.cpp.o</font>
[ 55%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/path_roundedcomposite.cpp.o</font>
[ 56%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/rigidbodyinertia.cpp.o</font>
[ 58%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/rotational_interpolation.cpp.o</font>
[ 59%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/rotational_interpolation_sa.cpp.o</font>
[ 61%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/rotationalinertia.cpp.o</font>
[ 62%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/segment.cpp.o</font>
[ 64%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/trajectory.cpp.o</font>
[ 65%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/trajectory_composite.cpp.o</font>
[ 67%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/trajectory_segment.cpp.o</font>
[ 68%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/trajectory_stationary.cpp.o</font>
[ 70%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/tree.cpp.o</font>
[ 71%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/treefksolverpos_recursive.cpp.o</font>
[ 73%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/treeidsolver_recursive_newton_euler.cpp.o</font>
[ 74%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/treeiksolverpos_nr_jl.cpp.o</font>
[ 76%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/treeiksolverpos_online.cpp.o</font>
[ 77%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/treeiksolvervel_wdls.cpp.o</font>
[ 79%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/treejnttojacsolver.cpp.o</font>
[ 80%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/ldl_solver_eigen.cpp.o</font>
[ 82%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/svd_HH.cpp.o</font>
[ 83%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/svd_eigen_HH.cpp.o</font>
[ 85%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/svd_eigen_Macie.cpp.o</font>
[ 86%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile.cpp.o</font>
[ 88%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile_dirac.cpp.o</font>
[ 89%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile_rect.cpp.o</font>
[ 91%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile_spline.cpp.o</font>
[ 92%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile_trap.cpp.o</font>
[ 94%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile_traphalf.cpp.o</font>
[ 95%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/error_stack.cxx.o</font>
[ 97%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/utility.cxx.o</font>
[ 98%] <font color="#4E9A06">Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/utility_io.cxx.o</font>
[100%] <font color="#8AE234"><b>Linking CXX shared library ../devel/lib/liborocos-kdl.so</b></font>
[100%] Built target orocos-kdl
</pre>



<pre><font color="#729FCF"><b>~/orocos_kinematics_dynamics/python_orocos_kdl/build</b></font>$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python2 (found suitable version &quot;2.7.17&quot;, minimum required is &quot;2&quot;) 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version &quot;2.7.17&quot;, minimum required is &quot;2.7&quot;) 
-- Using CATKIN_DEVEL_PREFIX: /home/cde/orocos_kinematics_dynamics/python_orocos_kdl/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/cde/orocos_kinematics_dynamics/python_orocos_kdl/build/test_results
-- Found gtest sources under &apos;/usr/src/googletest&apos;: gtests will be built
-- Found gmock sources under &apos;/usr/src/googletest&apos;: gmock will be built
CMake Warning (dev) at /usr/src/googletest/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run &quot;cmake --help-policy CMP0048&quot; for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/src/googletest/googlemock/CMakeLists.txt:40 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run &quot;cmake --help-policy CMP0048&quot; for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/src/googletest/googletest/CMakeLists.txt:47 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run &quot;cmake --help-policy CMP0048&quot; for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python2 (found version &quot;2.7.17&quot;) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- pybind11 v2.9.0 dev1
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cde/orocos_kinematics_dynamics/python_orocos_kdl/build
<font color="#8AE234"><b>cde@cde-MS-7A64</b></font>:<font color="#729FCF"><b>~/orocos_kinematics_dynamics/python_orocos_kdl/build</b></font>$ ls
<font color="#729FCF"><b>atomic_configure</b></font>  CMakeCache.txt          CTestCustom.cmake    Makefile
<font color="#729FCF"><b>catkin</b></font>            <font color="#729FCF"><b>CMakeFiles</b></font>              CTestTestfile.cmake  <font color="#729FCF"><b>pybind11</b></font>
<font color="#729FCF"><b>catkin_generated</b></font>  cmake_install.cmake     <font color="#729FCF"><b>devel</b></font>                <font color="#729FCF"><b>test_results</b></font>
CATKIN_IGNORE     CTestConfiguration.ini  <font color="#729FCF"><b>gtest</b></font>
<font color="#8AE234"><b>cde@cde-MS-7A64</b></font>:<font color="#729FCF"><b>~/orocos_kinematics_dynamics/python_orocos_kdl/build</b></font>$ make 
<font color="#AD7FA8"><b>Scanning dependencies of target PyKDL</b></font>
[ 16%] <font color="#4E9A06">Building CXX object CMakeFiles/PyKDL.dir/PyKDL/PyKDL.cpp.o</font>
[ 33%] <font color="#4E9A06">Building CXX object CMakeFiles/PyKDL.dir/PyKDL/frames.cpp.o</font>
[ 50%] <font color="#4E9A06">Building CXX object CMakeFiles/PyKDL.dir/PyKDL/kinfam.cpp.o</font>
[ 66%] <font color="#4E9A06">Building CXX object CMakeFiles/PyKDL.dir/PyKDL/framevel.cpp.o</font>
[ 83%] <font color="#4E9A06">Building CXX object CMakeFiles/PyKDL.dir/PyKDL/dynamics.cpp.o</font>
[100%] <font color="#8AE234"><b>Linking CXX shared module devel/lib/python2.7/dist-packages/PyKDL.so</b></font>
[100%] Built target PyKDL</pre>


As I Build both orocos_kdl and python_orocos_kdl from source, I am unable to find PyKDL as Source, I can not build PyKDL from any source.

**Comment by MatthijsBurgh** [comment]
When using the plain cmake/make, you need also to 'make install'. This is also in the install instructions.

This is not needed when using catkin.
