### ISSUE TITLE
error : dynamic  module does not define molule export function  (PyInit_PyKDL)

### ISSUE THREAD

**Issue by johnwaneboy** [orocos/orocos_kinematics_dynamics#364]
when I followed the instruction and installed orocos_kdl and python_orocos_kdl,  everything go well. But  when I run python3 ../tests/PyKDLtest.py,  error appears,   that is error : dynamic  module does not define molule export function  (PyInit_PyKDL). So what is the problem?

**Comment by johnwaneboy** [comment]
I have runned&nbsp;sudo ldconfig, but the error is still there.



---Original---
From: "Matthijs van der ***@***.***&gt;
Date: Wed, Oct 20, 2021 16:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [orocos/orocos_kinematics_dynamics] error : dynamic  module does not define molule export function  (PyInit_PyKDL) (Issue #364)




 
You missed step 10, running sudo ldconfig.

**Comment by MatthijsBurgh** [comment]
PyKDL is only a python wrapper of orocos_kdl, a CPP library. If those have a mismatch on the versions, stuff will not work.

So I need to know how you installed the CPP library.

Also what commit are you using when building PyKDL?

**Comment by johnwaneboy** [comment]
I installed the orocos_kdl following INSTALL.md in orcos_kinematic_dynamics/orocos_kdl
wane@wane:~/orocos_kinematics_dynamics/orocos_kdl/build$ cmake .. -DENABLE_TESTS:BOOL=ON
-- Orocos KDL version  (1.5.1)
-- Using CATKIN_DEVEL_PREFIX: /home/wane/orocos_kinematics_dynamics/orocos_kdl/build/devel
-- Using CMAKE_PREFIX_PATH: /home/wane/catkin_ws/devel;/opt/ros/melodic
-- This workspace overlays: /home/wane/catkin_ws/devel;/opt/ros/melodic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/wane/orocos_kinematics_dynamics/orocos_kdl/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9") 
-- Using Python nosetests: /usr/bin/nosetests
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- Build type set to 'Release' by user.
-- -- Looking for Cppunit - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wane/orocos_kinematics_dynamics/orocos_kdl/build
##########################################################################################
wane@wane:~/orocos_kinematics_dynamics/orocos_kdl/build$ make
[ 74%] Built target orocos-kdl
[ 77%] Built target treeinvdyntest
[ 80%] Built target velocityprofiletest
[ 84%] Built target kinfamtest
[ 87%] Built target inertiatest
[ 91%] Built target jacobiandottest
[ 93%] Built target framestest
[ 96%] Built target solvertest
[100%] Built target jacobiantest
#############################################################################################
wane@wane:~/orocos_kinematics_dynamics/orocos_kdl/build$ sudo make install
[sudo] password for wane: 
[ 74%] Built target orocos-kdl
[ 77%] Built target treeinvdyntest
[ 80%] Built target velocityprofiletest
[ 84%] Built target kinfamtest
[ 87%] Built target inertiatest
[ 91%] Built target jacobiandottest
[ 93%] Built target framestest
[ 96%] Built target solvertest
[100%] Built target jacobiantest
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/_setup_util.py
-- Installing: /usr/local/env.sh
-- Installing: /usr/local/setup.bash
-- Installing: /usr/local/local_setup.bash
-- Installing: /usr/local/setup.sh
-- Installing: /usr/local/local_setup.sh
-- Installing: /usr/local/setup.zsh
-- Installing: /usr/local/local_setup.zsh
-- Installing: /usr/local/.rosinstall
-- Up-to-date: /usr/local/share/orocos_kdl/package.xml
-- Up-to-date: /usr/local/share/orocos_kdl/cmake/FindEigen3.cmake
-- Up-to-date: /usr/local/share/orocos_kdl/cmake/orocos_kdl-config.cmake
-- Up-to-date: /usr/local/share/orocos_kdl/cmake/orocos_kdl-config-version.cmake
-- Up-to-date: /usr/local/share/orocos_kdl/cmake/OrocosKDLTargets.cmake
-- Installing: /usr/local/share/orocos_kdl/cmake/OrocosKDLTargets-release.cmake
-- Up-to-date: /usr/local/lib/pkgconfig/orocos-kdl.pc
-- Up-to-date: /usr/local/lib/pkgconfig/orocos_kdl.pc
-- Up-to-date: /usr/local/lib/liborocos-kdl.so.1.5.1
-- Up-to-date: /usr/local/lib/liborocos-kdl.so.1.5
-- Up-to-date: /usr/local/lib/liborocos-kdl.so
-- Up-to-date: /usr/local/include/kdl/articulatedbodyinertia.hpp
-- Up-to-date: /usr/local/include/kdl/chain.hpp
-- Up-to-date: /usr/local/include/kdl/chaindynparam.hpp
-- Up-to-date: /usr/local/include/kdl/chainexternalwrenchestimator.hpp
-- Up-to-date: /usr/local/include/kdl/chainfdsolver.hpp
-- Up-to-date: /usr/local/include/kdl/chainfdsolver_recursive_newton_euler.hpp
-- Up-to-date: /usr/local/include/kdl/chainfksolver.hpp
-- Up-to-date: /usr/local/include/kdl/chainfksolverpos_recursive.hpp
-- Up-to-date: /usr/local/include/kdl/chainfksolvervel_recursive.hpp
-- Up-to-date: /usr/local/include/kdl/chainhdsolver_vereshchagin.hpp
-- Up-to-date: /usr/local/include/kdl/chainidsolver.hpp
-- Up-to-date: /usr/local/include/kdl/chainidsolver_recursive_newton_euler.hpp
-- Up-to-date: /usr/local/include/kdl/chainidsolver_vereshchagin.hpp
-- Up-to-date: /usr/local/include/kdl/chainiksolver.hpp
-- Up-to-date: /usr/local/include/kdl/chainiksolverpos_lma.hpp
-- Up-to-date: /usr/local/include/kdl/chainiksolverpos_nr.hpp
-- Up-to-date: /usr/local/include/kdl/chainiksolverpos_nr_jl.hpp
-- Up-to-date: /usr/local/include/kdl/chainiksolvervel_pinv.hpp
-- Up-to-date: /usr/local/include/kdl/chainiksolvervel_pinv_givens.hpp
-- Up-to-date: /usr/local/include/kdl/chainiksolvervel_pinv_nso.hpp
-- Up-to-date: /usr/local/include/kdl/chainiksolvervel_wdls.hpp
-- Up-to-date: /usr/local/include/kdl/chainjnttojacdotsolver.hpp
-- Up-to-date: /usr/local/include/kdl/chainjnttojacsolver.hpp
-- Up-to-date: /usr/local/include/kdl/frameacc.hpp
-- Up-to-date: /usr/local/include/kdl/frameacc_io.hpp
-- Up-to-date: /usr/local/include/kdl/frames.hpp
-- Up-to-date: /usr/local/include/kdl/frames_io.hpp
-- Up-to-date: /usr/local/include/kdl/framevel.hpp
-- Up-to-date: /usr/local/include/kdl/framevel_io.hpp
-- Up-to-date: /usr/local/include/kdl/jacobian.hpp
-- Up-to-date: /usr/local/include/kdl/jntarray.hpp
-- Up-to-date: /usr/local/include/kdl/jntarrayacc.hpp
-- Up-to-date: /usr/local/include/kdl/jntarrayvel.hpp
-- Up-to-date: /usr/local/include/kdl/jntspaceinertiamatrix.hpp
-- Up-to-date: /usr/local/include/kdl/joint.hpp
-- Up-to-date: /usr/local/include/kdl/kdl.hpp
-- Up-to-date: /usr/local/include/kdl/kinfam.hpp
-- Up-to-date: /usr/local/include/kdl/kinfam_io.hpp
-- Up-to-date: /usr/local/include/kdl/motion.hpp
-- Up-to-date: /usr/local/include/kdl/path.hpp
-- Up-to-date: /usr/local/include/kdl/path_circle.hpp
-- Up-to-date: /usr/local/include/kdl/path_composite.hpp
-- Up-to-date: /usr/local/include/kdl/path_cyclic_closed.hpp
-- Up-to-date: /usr/local/include/kdl/path_line.hpp
-- Up-to-date: /usr/local/include/kdl/path_point.hpp
-- Up-to-date: /usr/local/include/kdl/path_roundedcomposite.hpp
-- Up-to-date: /usr/local/include/kdl/rigidbodyinertia.hpp
-- Up-to-date: /usr/local/include/kdl/rotational_interpolation.hpp
-- Up-to-date: /usr/local/include/kdl/rotational_interpolation_sa.hpp
-- Up-to-date: /usr/local/include/kdl/rotationalinertia.hpp
-- Up-to-date: /usr/local/include/kdl/segment.hpp
-- Up-to-date: /usr/local/include/kdl/solveri.hpp
-- Up-to-date: /usr/local/include/kdl/stiffness.hpp
-- Up-to-date: /usr/local/include/kdl/trajectory.hpp
-- Up-to-date: /usr/local/include/kdl/trajectory_composite.hpp
-- Up-to-date: /usr/local/include/kdl/trajectory_segment.hpp
-- Up-to-date: /usr/local/include/kdl/trajectory_stationary.hpp
-- Up-to-date: /usr/local/include/kdl/tree.hpp
-- Up-to-date: /usr/local/include/kdl/treefksolver.hpp
-- Up-to-date: /usr/local/include/kdl/treefksolverpos_recursive.hpp
-- Up-to-date: /usr/local/include/kdl/treeidsolver.hpp
-- Up-to-date: /usr/local/include/kdl/treeidsolver_recursive_newton_euler.hpp
-- Up-to-date: /usr/local/include/kdl/treeiksolver.hpp
-- Up-to-date: /usr/local/include/kdl/treeiksolverpos_nr_jl.hpp
-- Up-to-date: /usr/local/include/kdl/treeiksolverpos_online.hpp
-- Up-to-date: /usr/local/include/kdl/treeiksolvervel_wdls.hpp
-- Up-to-date: /usr/local/include/kdl/treejnttojacsolver.hpp
-- Up-to-date: /usr/local/include/kdl/velocityprofile.hpp
-- Up-to-date: /usr/local/include/kdl/velocityprofile_dirac.hpp
-- Up-to-date: /usr/local/include/kdl/velocityprofile_rect.hpp
-- Up-to-date: /usr/local/include/kdl/velocityprofile_spline.hpp
-- Up-to-date: /usr/local/include/kdl/velocityprofile_trap.hpp
-- Up-to-date: /usr/local/include/kdl/velocityprofile_traphalf.hpp
-- Up-to-date: /usr/local/include/kdl/frameacc.inl
-- Up-to-date: /usr/local/include/kdl/frames.inl
-- Up-to-date: /usr/local/include/kdl/framevel.inl
-- Up-to-date: /usr/local/include/kdl/config.h
-- Up-to-date: /usr/local/include/kdl/utilities/error.h
-- Up-to-date: /usr/local/include/kdl/utilities/error_stack.h
-- Up-to-date: /usr/local/include/kdl/utilities/kdl-config.h
-- Up-to-date: /usr/local/include/kdl/utilities/rall1d.h
-- Up-to-date: /usr/local/include/kdl/utilities/rall1d_io.h
-- Up-to-date: /usr/local/include/kdl/utilities/rall2d.h
-- Up-to-date: /usr/local/include/kdl/utilities/rall2d_io.h
-- Up-to-date: /usr/local/include/kdl/utilities/rallNd.h
-- Up-to-date: /usr/local/include/kdl/utilities/traits.h
-- Up-to-date: /usr/local/include/kdl/utilities/utility.h
-- Up-to-date: /usr/local/include/kdl/utilities/utility_io.h
-- Up-to-date: /usr/local/include/kdl/utilities/ldl_solver_eigen.hpp
-- Up-to-date: /usr/local/include/kdl/utilities/scoped_ptr.hpp
-- Up-to-date: /usr/local/include/kdl/utilities/svd_HH.hpp
-- Up-to-date: /usr/local/include/kdl/utilities/svd_eigen_HH.hpp
-- Up-to-date: /usr/local/include/kdl/utilities/svd_eigen_Macie.hpp
###################################################################################
wane@wane:~/orocos_kinematics_dynamics/orocos_kdl/build$ make check
UpdateCTestConfiguration  from :/home/wane/orocos_kinematics_dynamics/orocos_kdl/build/tests/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/wane/orocos_kinematics_dynamics/orocos_kdl/build/tests/DartConfiguration.tcl
Test project /home/wane/orocos_kinematics_dynamics/orocos_kdl/build/tests
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: framestest
Could not find executable framestest
Looked in the following places:
framestest
framestest
Release/framestest
Release/framestest
Debug/framestest
Debug/framestest
MinSizeRel/framestest
MinSizeRel/framestest
RelWithDebInfo/framestest
RelWithDebInfo/framestest
Deployment/framestest
Deployment/framestest
Development/framestest
Development/framestest

1: Test command: 
Unable to find executable: framestest
1/8 Test #1: framestest .......................***Not Run   0.00 sec
test 2
    Start 2: kinfamtest
Could not find executable kinfamtest
Looked in the following places:
kinfamtest
kinfamtest
Release/kinfamtest
Release/kinfamtest
Debug/kinfamtest
Debug/kinfamtest
MinSizeRel/kinfamtest
MinSizeRel/kinfamtest
RelWithDebInfo/kinfamtest
RelWithDebInfo/kinfamtest
Deployment/kinfamtest
Deployment/kinfamtest
Development/kinfamtest
Development/kinfamtest

2: Test command: 
Unable to find executable: kinfamtest
2/8 Test #2: kinfamtest .......................***Not Run   0.00 sec
test 3
    Start 3: solvertest
Could not find executable solvertest
Looked in the following places:
solvertest
solvertest
Release/solvertest
Release/solvertest
Debug/solvertest
Debug/solvertest
MinSizeRel/solvertest
MinSizeRel/solvertest
RelWithDebInfo/solvertest
RelWithDebInfo/solvertest
Deployment/solvertest
Deployment/solvertest
Development/solvertest
Development/solvertest

3: Test command: 
Unable to find executable: solvertest
3/8 Test #3: solvertest .......................***Not Run   0.00 sec
test 4
    Start 4: inertiatest
Could not find executable inertiatest
Looked in the following places:
inertiatest
inertiatest
Release/inertiatest
Release/inertiatest
Debug/inertiatest
Debug/inertiatest
MinSizeRel/inertiatest
MinSizeRel/inertiatest
RelWithDebInfo/inertiatest
RelWithDebInfo/inertiatest
Deployment/inertiatest
Deployment/inertiatest
Development/inertiatest
Development/inertiatest

4: Test command: 
Unable to find executable: inertiatest
4/8 Test #4: inertiatest ......................***Not Run   0.00 sec
test 5
    Start 5: jacobiantest
Could not find executable jacobiantest
Looked in the following places:
jacobiantest
jacobiantest
Release/jacobiantest
Release/jacobiantest
Debug/jacobiantest
Debug/jacobiantest
MinSizeRel/jacobiantest
MinSizeRel/jacobiantest
RelWithDebInfo/jacobiantest
RelWithDebInfo/jacobiantest
Deployment/jacobiantest
Deployment/jacobiantest
Development/jacobiantest
Development/jacobiantest

5: Test command: 
Unable to find executable: jacobiantest
5/8 Test #5: jacobiantest .....................***Not Run   0.00 sec
test 6
    Start 6: jacobiandottest
Could not find executable jacobiandottest
Looked in the following places:
jacobiandottest
jacobiandottest
Release/jacobiandottest
Release/jacobiandottest
Debug/jacobiandottest
Debug/jacobiandottest
MinSizeRel/jacobiandottest
MinSizeRel/jacobiandottest
RelWithDebInfo/jacobiandottest
RelWithDebInfo/jacobiandottest
Deployment/jacobiandottest
Deployment/jacobiandottest
Development/jacobiandottest
Development/jacobiandottest

6: Test command: 
Unable to find executable: jacobiandottest
6/8 Test #6: jacobiandottest ..................***Not Run   0.00 sec
test 7
    Start 7: velocityprofiletest
Could not find executable velocityprofiletest
Looked in the following places:
velocityprofiletest
velocityprofiletest
Release/velocityprofiletest
Release/velocityprofiletest
Debug/velocityprofiletest
Debug/velocityprofiletest
MinSizeRel/velocityprofiletest
MinSizeRel/velocityprofiletest
RelWithDebInfo/velocityprofiletest
RelWithDebInfo/velocityprofiletest
Deployment/velocityprofiletest
Deployment/velocityprofiletest
Development/velocityprofiletest
Development/velocityprofiletest

7: Test command: 
Unable to find executable: velocityprofiletest
7/8 Test #7: velocityprofiletest ..............***Not Run   0.00 sec
test 8
    Start 8: treeinvdyntest
Could not find executable treeinvdyntest
Looked in the following places:
treeinvdyntest
treeinvdyntest
Release/treeinvdyntest
Release/treeinvdyntest
Debug/treeinvdyntest
Debug/treeinvdyntest
MinSizeRel/treeinvdyntest
MinSizeRel/treeinvdyntest
RelWithDebInfo/treeinvdyntest
RelWithDebInfo/treeinvdyntest
Deployment/treeinvdyntest
Deployment/treeinvdyntest
Development/treeinvdyntest
Development/treeinvdyntest

8: Test command: 
Unable to find executable: treeinvdyntest
8/8 Test #8: treeinvdyntest ...................***Not Run   0.00 sec

0% tests passed, 8 tests failed out of 8

Total Test time (real) =   0.00 sec

The following tests FAILED:
	  1 - framestest (Not Run)
	  2 - kinfamtest (Not Run)
	  3 - solvertest (Not Run)
	  4 - inertiatest (Not Run)
	  5 - jacobiantest (Not Run)
	  6 - jacobiandottest (Not Run)
	  7 - velocityprofiletest (Not Run)
	  8 - treeinvdyntest (Not Run)
Errors while running CTest
tests/CMakeFiles/check.dir/build.make:57: recipe for target 'tests/CMakeFiles/check' failed
make[3]: *** [tests/CMakeFiles/check] Error 8
CMakeFiles/Makefile2:582: recipe for target 'tests/CMakeFiles/check.dir/all' failed
make[2]: *** [tests/CMakeFiles/check.dir/all] Error 2
CMakeFiles/Makefile2:589: recipe for target 'tests/CMakeFiles/check.dir/rule' failed
make[1]: *** [tests/CMakeFiles/check.dir/rule] Error 2
Makefile:331: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by MatthijsBurgh** [comment]
Closing this issue in 5 days, when no response is given.
