### ISSUE TITLE
Can't run the test 

### ISSUE THREAD

**Issue by bhomaidan1990** [orocos/orocos_kinematics_dynamics#365]
Hi, I have followed the [installation instructions](https://github.com/orocos/orocos_kinematics_dynamics/blob/master/python_orocos_kdl/INSTALL.md#without-catkin), but when I have reached the execution of the tests `Python 3: python3 ../tests/PyKDLtest.py` I have got the following error:

```
git/orocos_kinematics_dynamics/python_orocos_kdl/build$ python3 ../tests/PyKDLtest.py
Traceback (most recent call last):
  File "../tests/PyKDLtest.py", line 26, in <module>
    import dynamicstest
  File "/home/belal/git/orocos_kinematics_dynamics/python_orocos_kdl/tests/dynamicstest.py", line 24, in <module>
    from PyKDL import *
ImportError: liborocos-kdl.so.1.4: cannot open shared object file: No such file or directory
```
Note that the `liborocos-kdl.so.1.5` exists, and not `liborocos-kdl.so.1.4`

**Comment by MatthijsBurgh** [comment]
Oh you are using catkin, why didn't you use the catkin install instructions?

**Comment by MatthijsBurgh** [comment]
You might have also removed files of system installed packages

**Comment by MatthijsBurgh** [comment]
Closing this issue in 6 days, when no response is given.
