### ISSUE TITLE
Question of gym-gazebo 

### ISSUE THREAD

**Issue by kankanzheli** [orocos/orocos_kinematics_dynamics#379]
I'm very sorry to ask this question here. I have a question about gym gazebo. My running environment is as follows:
Ubntu18.04
ROS-Melodic
python: python2.7
gym0.16.0
gazebo9.0.0

The installation process was quite smooth. But when I runned the example of gym-gazebo(circuit_turtlebot_lidar_qlearn.py), the following error occured:

[ERROR] [1643889037.781025, 146.790000]: Spawn service failed. Exiting.
[spawn_turtlebot_model-3] process has died [pid 10199, exit code 1, cmd /home/zhaowentao/ROS/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/spawn_model -unpause -urdf -param robot_description -model mobile_base __name:=spawn_turtlebot_model __log:=/home/zhaowentao/.ros/log/7f7bce36-84e7-11ec-84f6-02429b0b1025/spawn_turtlebot_model-3.log].
log file: /home/zhaowentao/.ros/log/7f7bce36-84e7-11ec-84f6-02429b0b1025/spawn_turtlebot_model-3*.log

How to solve that problem???

**Comment by MatthijsBurgh** [comment]
This is really not the repo for this issue. Not even close.

I think you have to be at https://github.com/erlerobot/gym-gazebo or https://github.com/AcutronicRobotics/gym-gazebo2. Or at [`gazebo_ros_pkgs`](https://github.com/ros-simulation/gazebo_ros_pkgs).
