### ISSUE TITLE
PyKDL: specifying a root name when intializing a Tree causes segfault

### ISSUE THREAD

**Issue by jf---** [orocos/orocos_kinematics_dynamics#42]
``` python
from PyKDL import Tree
ohno = Tree(root_name="carrot")
# kaboom
```

Segmentation fault: 11

**Comment by smits** [comment]
Can you provide a backtrace?

R.

On Thu, Jan 15, 2015 at 11:51 AM, Jelle Feringa <notifications@github.com>
wrote:

> from PyKDL import Tree
> ohno = Tree(root_name="carrot")# kaboom
>
> Segmentation fault: 11
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orocos/orocos_kinematics_dynamics/issues/42>.
>



-- 
Ruben Smits, Roboticist - Founder
+32 479 511 786
Intermodalics - Kapeldreef 60, 3001 Heverlee - BELGIUM
www.intermodalics.eu

**Comment by jf---** [comment]
Sorry Ruben, since this leads to a segfault I can't really do so...
Or do you mean a GDB trace?

**Comment by jf---** [comment]
Btw, I noticed that trying to access a non-existing segment, results into segfault.
I guess you'd expect a ValueError to be raised

```python
chain.getSegment( chain.getNrOfSegments() + 1 )
# poooof -> segfault
```

**Comment by smits** [comment]
I would indeed need a gdb trace. And there is indeed no index checking in the getSegment function: https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/src/chain.cpp#L68-L71

**Comment by zchen24** [comment]
@jf--- @smits #145 should fix this.

**Comment by MatthijsBurgh** [comment]
@jf--- please close this issue, if fixed
