### ISSUE TITLE
ROS2 compatibility

### ISSUE THREAD

**Issue by BenBlumer** [orocos/orocos_kinematics_dynamics#473]
Is there a ROS2 release? Or a preferred way to build for ROS2? (I'm aiming to get Python bindings compatible with Jazzy).

I've seen, e.g., this package:  https://github.com/ros2-gbp/orocos_kinematics_dynamics-release  Is that the best strategy?

**Comment by MatthijsBurgh** [comment]
The ROS2 package can be found here: https://github.com/ros2/orocos_kdl_vendor
