### ISSUE TITLE
JointType typedef broken by None define in X11 library

### ISSUE THREAD

**Issue by alexander-hagg** [orocos/orocos_kinematics_dynamics#48]
We use the Stage Simulator and KDL in combination for a robotics course and stumbled upon a problem that arose in KDL 1.3.

In joint.hpp line 47:
`typedef enum { RotAxis,RotX,RotY,RotZ,TransAxis,TransX,TransY,TransZ,None} JointType;`

The None type was already defined in X11/X.h and hat to be undef, as we otherwise would get the following error when compiling our code.

`enum expected identifier before numeric constant`

Fix: add `#undef None` before typedef.

**Comment by MatthijsBurgh** [comment]
outdated
