### ISSUE TITLE
version tags incompatible with rosinstall_generator --upstream

### ISSUE THREAD

**Issue by v4hn** [orocos/orocos_kinematics_dynamics#56]
Hey everyone,

I'd like to use a rather unknown but useful feature of rosinstall_generator to construct my ros-workspace:
`rosinstall_generator --upstream`

This ignores the \*-release repository overhead and directly fetches the upstream source repository
of a ros-module into the workspace.
Now this works great with all of ROS, but it fails to work with *this* project and that's the reason for this issue:
rosinstall_generator expects the versions released into ROS to exist as tags in the upstream
repository. However, your current version tag is called "v1.3.0" instead of "1.3.0" (the version).

The most easy way to fix this would be to also add a tag without the leading "v" in your repository.
It would be *great* if you could do that.

**Comment by smits** [comment]
Done ;)
