### ISSUE TITLE
JntArray::Equal does not always work

### ISSUE THREAD

**Issue by pbeeson** [orocos/orocos_kinematics_dynamics#57]
I noticed that doing a `KDL::Equal(q_out,KDL:JntArray(q_out.rows()),1000)` always returns false.  That's a HUGE epsilon, and it's false.  I tracked the down to a change in KDL, where the hand-coded equal that looped through the array was replaced by the Eigen `isApprox()` function.  Apparently, is Approx does not work when either of the vectors is very close to zero.  This seems bad/wrong.

http://eigen.tuxfamily.org/dox/classEigen_1_1DenseBase.html#a158c2184951e6e415c2e9b98db8e8966

What you wanted for arrays a & b was probably something like:

`isZero(a.data-b.data,eps)`

**Comment by pbeeson** [comment]
This is a pretty large and important bug.  I would have hoped someone would have addressed this by now.

**Comment by smits** [comment]
I'll add a unittest for this specific case and see if your proposal fixes that specific issue.

**Comment by pbeeson** [comment]
For some reason, the HEAD for the KDL source code still uses isApprox() for a JntArray::Equal(), which makes Equal() return False almost always for two equally sized joint arrays (Because of the size of the array).  This really should be properly fixed.

**Comment by MatthijsBurgh** [comment]
@pbeeson I have tested this in PyKDL. I eexperienced the problem you describe. I have create a PR, #262, which gets rid of `isApprox` entirely.
