### ISSUE TITLE
PyKDL.so is installed to lib64

### ISSUE THREAD

**Issue by cottsay** [orocos/orocos_kinematics_dynamics#75]
ROS only uses the "lib" directory, but PyKDL.so is getting installed to lib64.

The offending code is at https://github.com/orocos/orocos_kinematics_dynamics/blob/master/python_orocos_kdl/CMakeLists.txt#L12

Right now, PyKDL.so is the ONLY thing that ends up in lib64 when building "desktop-full" for Jade on Fedora.

Thanks,

--scott

**Comment by smits** [comment]
Do you have a proposal on how to fix this without breaking non-ROS builds?

**Comment by MatthijsBurgh** [comment]
I think this is not relevant anymore, please close.
