### ISSUE TITLE
Rotation::Quaternion may return invalid rotation matrix

### ISSUE THREAD

**Issue by wannesvanloock** [orocos/orocos_kinematics_dynamics#79]
Constructing a rotation matrix from a non unit quaternion results in an invalid rotation matrix. It should either fail or return a valid rotation matrix as e.g. explained [here](https://en.wikipedia.org/wiki/Rotation_matrix#Quaternion).

**Comment by smits** [comment]
Could you propose a fix for this?

**Comment by MatthijsBurgh** [comment]
outdated
