### ISSUE TITLE
Release 1.3.1 for ROS kinetic?

### ISSUE THREAD

**Issue by meyerj** [orocos/orocos_kinematics_dynamics#88]
ROS kinetic currently has version 1.3.0 only, while indigo and jade have 1.3.1:
http://repositories.ros.org/status_page/compare_indigo_jade_kinetic.html?q=orocos_kinematics_dynamics

Diff from 1.3.0 to 1.3.1:
https://github.com/orocos/orocos_kinematics_dynamics/compare/v1.3.0...v1.3.1

**Comment by smits** [comment]
Feel free to release 1.3.1 in kinetic. I guess we just accidently forgot.

**Comment by meyerj** [comment]
Done: https://github.com/ros/rosdistro/pull/13304
