### ISSUE TITLE
Can't make orocos-kdl-models with Qt

### ISSUE THREAD

**Issue by yn-coder** [orocos/orocos_kinematics_dynamics#98]
Trying to build kdl with Qt, and got error on `orocos-kdl-models` building,

Qt work with Visual C++ compiler, main application is builded, but `orocos-kdl-models` raise error 

`NMAKE:-1: error: U1073: don't know how to make 'models\orocos-kdl-models.lib'`

Can you help?

**Comment by yn-coder** [comment]
Right now I just cut the `SHARED ` from `ADD_LIBRARY(orocos-kdl-models SHARED puma560.cpp kukaLWR_DHnew.cpp)` and got a statical lib, and it's working - but it could be a rought way

**Comment by MatthijsBurgh** [comment]
outdated
